set DB_TYPE=ms_sql
set MS_HOST=10.1.1.3
set MS_USER=sa
set MS_PASSWORD=system
set MS_DB=genetix_test_sokolov
set MS_INST=MSSQLSERVER
set MS_PORT=1433
set MY_HOST=localhost
set MY_USER=sa
set MY_PASSWORD=system
set MY_DB=genetix_test
node memserver.js